export const GET_USERS_ASYNC = 'GET_USERS_ASYNC';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';

export const ADD_USER_ASYNC = 'ADD_USER_ASYNC';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
